### ISSUE TITLE
Feature request: add struct to save the original assigned value in each field 

### ISSUE THREAD

**Issue by Jerry-Ma** [BlackMATov/enum.hpp#12]
Hi,

It would be nice to be able to retrieve the original representation of each
field via the traits class:

```
ENUM_HPP_CLASS_DECL(Flag, int,
              (FlagA = 1 << 0)
              (FlagB = 1 << 1)
              (FlagC = 1 << 2)
              (FlagD = FlagA | FlagB | FlagC)
              (FlagE = FlagB | FlagC)
              );
ENUM_HPP_REGISTER_TRAITS(Flag)

static_assert(Flag_traits::to_repr(Flag::FlagE) == "FlagB | FlagC");
```

This would allow a more human readable representation when serialized.

Thank you!

**Comment by BlackMATov** [comment]
Hello!

Hm.. I'll try to impl it 👍

**Comment by BlackMATov** [comment]
I've just tried to make it in a branch (feature/value_string). But I have several issues now:
- external enums doesn't support;
- some ambiguities with "field_a | field_b" vs "field_a|field_b" and etc.

Due to these issues, I cannot add this to the main branch, but you can fork your own with these changes from the feature branch.

**Comment by Jerry-Ma** [comment]
Hi,

Thank you for such prompt reply! And I just checked the code, it is just what I needed.

In fact, I didn't envision a `from_value_string` method, for the exact reason that you just mentioned about ambiguity in the value string. I think it would be too much to try to come up with a good strategy to "normalize" the value string.

For my use case, I would like to rely on the value_string to provide some more verbose diagnostic messages for bit flags that are composed with multiple existing flags. A to_value_string method does the job perfectly.

Again, that you for the help!
